name: Create artifact (zip) on tag
run-name: ${{ github.actor }} set a tag

on:
  push:
    tags:
      - '*'
      # - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci

      - run: npm run build --if-present
      - run: npm test --if-present
      # - run: npm lint --if-present

      - run: echo "PACKAGE_JSON=$(jq -c . < package.json)" >> $GITHUB_ENV
      - name: Zip build
        run: |
          cd ./dist/${{ fromJson(env.PACKAGE_JSON).name }}
          zip -r '../${{ fromJson(env.PACKAGE_JSON).name }}_${{ fromJson(env.PACKAGE_JSON).version }}.zip' ./

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/apps/*.zip
